import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';
import {
	ClerkProvider,
	Show,
	SignInButton,
	SignUpButton,
	UserButton,
} from '@clerk/nextjs';
import { dark } from '@clerk/ui/themes';
import type { Metadata } from 'next';
import { IBM_Plex_Mono, Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

const plexMono = IBM_Plex_Mono({
	subsets: ['latin'],
	variable: '--font-plex-mono',
	weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn('antialiased', inter.variable, plexMono.variable)}
			suppressHydrationWarning
		>
			<body suppressHydrationWarning>
				<ClerkProvider
					appearance={{
						theme: dark,
					}}
				>
					<ThemeProvider
						attribute="class"
						defaultTheme="dark"
						enableSystem
						disableTransitionOnChange
					>
						<header className="flex justify-end items-center p-4 gap-4 h-16">
							<Show when="signed-out">
								<SignInButton />
								<SignUpButton>
									<button className="bg-purple-700 text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
										Sign Up
									</button>
								</SignUpButton>
							</Show>
							<Show when="signed-in">
								<UserButton />
							</Show>
						</header>
						{children}
					</ThemeProvider>
				</ClerkProvider>
			</body>
		</html>
	);
}
